# GPIO Enable
CONFIG_GPIO=y

# SPI
CONFIG_SPI=y

# Flash
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_SPI_NOR=y

# Disk Access layer
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_FLASH=y

# FATFS
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FAT_FILESYSTEM_ELM=y

# Required for FAT
CONFIG_FS_FATFS_MOUNT_MKFS=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_MAX_LFN=255

# Logging (optional but useful)
CONFIG_LOG=y
CONFIG_FS_LOG_LEVEL_DBG=y

# FATFS + mkfs path can consume noticeable stack in main thread
CONFIG_MAIN_STACK_SIZE=4096

# Allow FATFS volume name to match flash-disk disk-name ("FLASH_DISK")
CONFIG_FS_FATFS_CUSTOM_MOUNT_POINT_COUNT=1
CONFIG_FS_FATFS_CUSTOM_MOUNT_POINTS="FLASH_DISK"

CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096

CONFIG_SMF=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
